apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos-stream10-aqua-mollusk-27
  namespace: openshift-gitops
spec:
  dataVolumeTemplates:
    - metadata:
        name: centos-stream10-aqua-mollusk-27-volume
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream10
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '34087042032'
          storageClassName: hostpath
  instancetype:
    name: u1.medium
  preference:
    name: centos.stream10
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks: []
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: centos-stream10-aqua-mollusk-27-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: fu4u-e7r1-idun
              user: centos
          name: cloudinitdisk
